### ISSUE TITLE
auto role update issue?

### ISSUE THREAD

**Issue by SajidZakaria** [ParsaAlizadeh/TLE#10]
after auto roleupdate has been has been enabled, the result of the same contest publishes multiple times. Is this an issue with auto role update?

**Comment by ParsaAlizadeh** [comment]
Did bot restart between publishes?
Publishing rating changes is based on a delay (36 hours) and cache database. Cache database is not on Heroku Postgres and reset on every restart.
https://github.com/ParsaAlizadeh/TLE/blob/3c214f07554d274fc5748daa5ac5306d8e38e987/tle/util/cache_system2.py#L404-L408

**Comment by ParsaAlizadeh** [comment]
Closed by #19
