### ISSUE TITLE
;handle list truncated

### ISSUE THREAD

**Issue by SajidZakaria** [ParsaAlizadeh/TLE#13]
We have as server where 90+ members are identified in TLE. But the list of first 80 are truncated, only 14 are shown. But the other queries work just fine for people who's names are truncated from the list.

**Comment by ParsaAlizadeh** [comment]
`;handle list` creates a page embed. Reacting `◀️` or `▶️` should change the page and shows other members. Is this an issue from page functionality? I don't see any problem from my own instance.

**Comment by SajidZakaria** [comment]
No no. The embed thing is obvious. I know how it works. So now take my problem just as it says. Out of 94 identified users, it only shows 14.  The picture below could a bit explanatory. There are just these 14, and no extra pages on embed. And @Bruteforcekid is identified but not present on the list. The case is same for 80 others.
![image](https://user-images.githubusercontent.com/30206752/125154250-eb9b1100-e17a-11eb-9908-a24d9d2a2afd.png)

**Comment by ParsaAlizadeh** [comment]
As I see in the image, I guess it recognizes only ~14~ 15 handles as active members. Lets try this:
1. Enable `Server Members Intent` in [Discord Developer Portal](https://discord.com/developers/applications) (Bot settings).
2. Run `;_updatestatus`. It shows number of active handles. (should be 94)
3. Try `;handle list` again.

**Comment by SajidZakaria** [comment]
Thanks <3 It worked. Sorry for late response.

**Comment by SajidZakaria** [comment]
Thanks <3 It worked. Sorry for late response.
