### ISSUE TITLE
Postgress url how to change color name

### ISSUE THREAD

**Issue by MashrurHossainZuha** [ParsaAlizadeh/TLE#21]
I recently tried set up an instance of the bot for my server, bt couldnt add a addon with the name of HEROKU_POSTGRESQL_BLUE_URL, as the color name is rng, its annoying, and without the exact color name in the config var the worker is showing an error in heroku log, can you please change that somehow or tell how do i add a specific color for heroku addon.

**Comment by ParsaAlizadeh** [comment]
If it assigned the url to another color, copy the url (in settings, config vars) and create the blue one manually.

**Comment by MashrurHossainZuha** [comment]
Actually I did do exactly that, i dont know why but the manually created blue variable was deleted automatically, is some kind of bug or smthing?
